update readme.adoc
In my experience, these tools are required to properly import the table to an app.

Without those, errors will arise during compile (if the module is imported), for instance, without @angular/material and @angular/cdk:
```
Error: The target entry-point "@i-cell/data-table" has missing dependencies:
 - @angular/material/paginator
 - @angular/cdk/a11y
 - @angular/cdk/coercion
 - @angular/cdk/collections
 - @angular/material/sort
 - @angular/material/table
 - @angular/cdk/drag-drop
 - @angular/material/autocomplete
 - @angular/material/button
 - @angular/material/checkbox
 - @angular/material/datepicker
 - @angular/material/divider
 - @angular/material/icon
 - @angular/material/input
 - @angular/material/menu
 - @angular/material/progress-spinner
 - @angular/material/select
 - @angular/material/tooltip
 - @angular/material/core
 - @angular/cdk/table

```